// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.security;

import com.app2.app2t.domain.security.AppRole;

privileged aspect AppRole_Roo_JavaBean {
    
    public String AppRole.getRoleName() {
        return this.RoleName;
    }
    
    public void AppRole.setRoleName(String RoleName) {
        this.RoleName = RoleName;
    }
    
}
